export const ecosystemData = {
  hero: {
    name: "Stephen Burch",
    title: "AI Architect | Autonomous Systems Builder",
    subtitle: "Founder of Ghost AI",
    bio: "I design and deploy self-operating AI systems for lead generation, sales automation, financial intelligence, and autonomous voice orchestration.",
  },
  
  tier1: [
    {
      id: "ghost-mind",
      name: "🧠 GhostMIND",
      shortName: "GhostMIND",
      role: "AI CEO / Orchestrator",
      description: "Central command center for multi-agent orchestration",
      features: [
        "Command interface for agent spawning",
        "Task routing & decision logic",
        "Airtable + API control layer",
        "Sub-agent coordination",
      ],
      repo: "Nova-CEO",
      repoUrl: "https://github.com/burchdad/Nova-CEO",
      status: "Active Development",
      stack: ["Python", "FastAPI", "OpenAI", "Airtable"],
      tier: 1,
    },
    {
      id: "ghost-crm",
      name: "📊 GhostCRM",
      shortName: "GhostCRM",
      role: "AI-Native Revenue Engine",
      description: "Sales automation & lead management platform",
      features: [
        "AI-powered lead tracking",
        "Automated follow-ups",
        "Voice + SMS integrations",
        "Sales pipeline automation",
        "Custom workflow builder",
      ],
      repo: "ghostcrm",
      repoUrl: "https://github.com/burchdad/ghostcrm",
      status: "Active Development",
      stack: ["TypeScript", "React", "Twilio", "Stripe"],
      tier: 1,
    },
    {
      id: "ghost-score",
      name: "💳 GhostScore",
      shortName: "GhostScore",
      role: "Financial Intelligence Engine",
      description: "Credit optimization & FICO simulation",
      features: [
        "FICO scoring simulations",
        "Credit optimization strategies",
        "Scenario modeling engine",
        "PDF report parsing",
        "AI recommendations",
      ],
      repo: "Ghostscore",
      repoUrl: "https://github.com/burchdad/Ghostscore",
      status: "Active Development",
      stack: ["Python", "HTML", "FastAPI"],
      tier: 1,
    },
    {
      id: "ghost-voice-os",
      name: "🎙️ Ghost Voice OS",
      shortName: "Voice OS",
      role: "Human-AI Interaction Layer",
      description: "Real-time voice AI & conversational agent system",
      features: [
        "Real-time voice processing",
        "Streaming text-to-speech",
        "AI voice cloning",
        "Call automation (Twilio/Telnyx)",
        "Conversational context awareness",
      ],
      repo: "ghost-voice-os",
      repoUrl: "https://github.com/burchdad/ghost-voice-os",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Twilio", "OpenAI"],
      tier: 1,
    },
  ],

  tier2: [
    {
      id: "piddy",
      name: "🤖 Piddy",
      shortName: "Piddy",
      role: "Autonomous Developer Agent",
      description: "Self-operating AI that writes, tests, and improves code",
      features: [
        "Autonomous code generation",
        "Self-healing architecture",
        "Multi-model fallback (Claude → OpenAI → local)",
        "Offline-capable vision system",
        "Continuous learning",
      ],
      repo: "Piddy",
      repoUrl: "https://github.com/burchdad/Piddy",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Claude", "OpenAI"],
      tier: 2,
    },
    {
      id: "piddy-microservices",
      name: "⚙️ Piddy Microservices",
      shortName: "Piddy Microservices",
      role: "Distributed Agent Architecture",
      description: "Microservice architecture for autonomous agent scaling",
      features: [
        "Distributed agent spawning",
        "Service orchestration",
        "Inter-agent communication",
        "Load balancing",
      ],
      repo: "piddy-microservices",
      repoUrl: "https://github.com/burchdad/piddy-microservices",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Docker"],
      tier: 2,
    },
    {
      id: "ghost-drop",
      name: "📦 GhostDrop",
      shortName: "GhostDrop",
      role: "Productized Automation System",
      description: "AI funnel builder for businesses",
      features: [
        "Auto-generate sales funnels",
        "Chatbot builders",
        "Follow-up automation",
        "Airtable-based workflows",
        "Zero-code configuration",
      ],
      repo: "ghostdrop",
      repoUrl: "https://github.com/burchdad/ghostdrop",
      status: "Active Development",
      stack: ["JavaScript", "React", "Airtable"],
      tier: 2,
    },
    {
      id: "ghost-investor",
      name: "🧾 Ghost Investor AI",
      shortName: "GhostCFO",
      role: "Financial Analysis & Underwriting",
      description: "Investment analysis and deal evaluation engine",
      features: [
        "Deal structure analysis",
        "CapEx estimation",
        "ROI modeling",
        "Image-based underwriting",
        "Predictive modeling",
      ],
      repo: "ghost-investor-ai",
      repoUrl: "https://github.com/burchdad/ghost-investor-ai",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Machine Learning"],
      tier: 2,
    },
    {
      id: "ghost-table",
      name: "📋 GhostTable",
      shortName: "GhostTable",
      role: "Airtable-Alternative Data Layer",
      description: "Lightweight database & table management for Ghost systems",
      features: [
        "Relational data management",
        "Real-time sync",
        "API integrations",
        "Query optimization",
      ],
      repo: "ghosttable",
      repoUrl: "https://github.com/burchdad/ghosttable",
      status: "Active Development",
      stack: ["TypeScript", "React", "Node.js"],
      tier: 2,
    },
  ],

  tier3: [
    {
      id: "investor-command-center",
      name: "🎯 Investor Command Center",
      shortName: "Investor Command Center",
      role: "R&D: Portfolio Orchestration",
      description: "Experimental multi-agent investment oversight system",
      features: [
        "Real-time portfolio tracking",
        "Multi-agent coordination",
        "Deal flow management",
      ],
      repo: "investor-command-center",
      repoUrl: "https://github.com/burchdad/investor-command-center",
      status: "Experimental",
      stack: ["Python", "FastAPI"],
      tier: 3,
    },
    {
      id: "tldr-agent",
      name: "📄 TLDR Agent",
      shortName: "TLDR Agent",
      role: "R&D: Content Intelligence",
      description: "Autonomous document analysis and summarization",
      features: [
        "PDF/document parsing",
        "AI summarization",
        "Key insights extraction",
      ],
      repo: "tldr-agent-demo",
      repoUrl: "https://github.com/burchdad/tldr-agent-demo",
      status: "Experimental",
      stack: ["TypeScript", "OpenAI"],
      tier: 3,
    },
    {
      id: "piddy-growth",
      name: "🧬 Piddy Growth",
      shortName: "Piddy Growth",
      role: "R&D: Autonomous Learning",
      description: "Self-improving agent learning system",
      features: [
        "Continuous skill acquisition",
        "Experience replay",
        "Performance optimization",
      ],
      repo: "piddy-growth",
      repoUrl: "https://github.com/burchdad/piddy-growth",
      status: "Experimental",
      stack: ["Python"],
      tier: 3,
    },
  ],

  infrastructure: [
    {
      name: "Integrations",
      items: [
        "Stripe (payments & billing)",
        "Twilio (SMS & voice calls)",
        "Telnyx (carrier APIs)",
        "Mailchimp (email campaigns)",
        "Airtable (workflow logic)",
        "Zapier (automation backbone)",
        "Google Drive (report storage)",
        "People Data Labs (enrichment)",
      ]
    },
    {
      name: "AI Stack",
      items: [
        "OpenAI (GPT-4, 3.5)",
        "Anthropic (Claude)",
        "Local LLM (future)",
        "Voice AI",
      ]
    },
    {
      name: "Tech Stack",
      items: [
        "Python + FastAPI (backends)",
        "TypeScript + React (frontends)",
        "Node.js (services)",
        "Supabase (databases)",
        "Docker (containerization)",
      ]
    }
  ]
};
