export const ecosystemData = {
  hero: {
    name: "Stephen Burch",
    title: "Building Autonomous AI Systems That Replace Entire Business Functions",
    subtitle: "Founder of Ghost AI",
    bio: "I design and deploy AI-powered platforms that automate sales, generate leads, optimize credit intelligence, and orchestrate voice-based AI. The Ghost ecosystem is a complete autonomous operating system for businesses.",
    cta1: "Explore Ecosystem",
    cta2: "View on GitHub",
  },
  
  tier1: [
    {
      id: "ghost-mind",
      name: "🧠 GhostMIND",
      shortName: "GhostMIND",
      role: "AI CEO / Orchestrator",
      description: "Central command center for multi-agent orchestration",
      longDescription: "WHAT: Multi-agent orchestration engine that coordinates all Ghost systems as one unified AI CEO. WHY: Businesses need a single decision-making layer that controls, prioritizes, and routes tasks across AI agents. IMPACT: Turns disconnected AI tools into a single autonomous business operator.",
      features: [
        "Command interface for agent spawning",
        "Task routing & decision logic",
        "Airtable + API control layer",
        "Sub-agent coordination",
      ],
      repo: "Nova-CEO",
      repoUrl: "https://github.com/burchdad/Nova-CEO",
      status: "Active Development",
      stack: ["Python", "FastAPI", "OpenAI", "Airtable"],
      tier: 1,
    },
    {
      id: "ghost-crm",
      name: "📊 GhostCRM",
      shortName: "GhostCRM",
      role: "AI-Native Revenue Engine",
      description: "Sales automation & lead management platform",
      longDescription: "WHAT: AI-powered CRM that automatically qualifies leads, sends follow-ups, and manages entire sales pipelines without human intervention. WHY: Sales teams waste 60% of time on admin work. GhostCRM eliminates that. IMPACT: Businesses close more deals 5x faster with AI handling discovery, qualification, and nurturing.",
      features: [
        "AI-powered lead tracking",
        "Automated follow-ups",
        "Voice + SMS integrations",
        "Sales pipeline automation",
        "Custom workflow builder",
      ],
      repo: "ghostcrm",
      repoUrl: "https://github.com/burchdad/ghostcrm",
      status: "Active Development",
      stack: ["TypeScript", "React", "Twilio", "Stripe"],
      tier: 1,
    },
    {
      id: "ghost-score",
      name: "💳 GhostScore",
      shortName: "GhostScore",
      role: "Financial Intelligence Engine",
      description: "Credit optimization & FICO simulation",
      longDescription: "WHAT: AI engine that simulates credit score changes and recommends specific actions to improve FICO scores and financial health. WHY: Users don't know how to improve credit—this automates the strategy. IMPACT: Helps thousands optimize credit faster, qualify for loans, and understand financial leverage points.",
      features: [
        "FICO scoring simulations",
        "Credit optimization strategies",
        "Scenario modeling engine",
        "PDF report parsing",
        "AI recommendations",
      ],
      repo: "Ghostscore",
      repoUrl: "https://github.com/burchdad/Ghostscore",
      status: "Active Development",
      stack: ["Python", "HTML", "FastAPI"],
      tier: 1,
    },
    {
      id: "ghost-voice-os",
      name: "🎙️ Ghost Voice OS",
      shortName: "Voice OS",
      role: "Human-AI Interaction Layer",
      description: "Real-time voice AI & conversational agent system",
      longDescription: "WHAT: Real-time voice AI system that answers calls, books appointments, and handles customer conversations with natural language comprehension. WHY: Businesses need 24/7 AI handling phone calls and customer interactions. IMPACT: Replaces entire customer service teams with AI that works 24/7, 365 days a year.",
      features: [
        "Real-time voice processing",
        "Streaming text-to-speech",
        "AI voice cloning",
        "Call automation (Twilio/Telnyx)",
        "Conversational context awareness",
      ],
      repo: "ghost-voice-os",
      repoUrl: "https://github.com/burchdad/ghost-voice-os",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Twilio", "OpenAI"],
      tier: 1,
    },
  ],

  tier2: [
    {
      id: "piddy",
      name: "🤖 Piddy",
      shortName: "Piddy",
      role: "Autonomous Developer Agent",
      description: "Self-operating AI that writes, tests, and improves code",
      features: [
        "Autonomous code generation",
        "Self-healing architecture",
        "Multi-model fallback (Claude → OpenAI → local)",
        "Offline-capable vision system",
        "Continuous learning",
      ],
      repo: "Piddy",
      repoUrl: "https://github.com/burchdad/Piddy",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Claude", "OpenAI"],
      tier: 2,
    },
    {
      id: "piddy-microservices",
      name: "⚙️ Piddy Microservices",
      shortName: "Piddy Microservices",
      role: "Distributed Agent Architecture",
      description: "Microservice architecture for autonomous agent scaling",
      features: [
        "Distributed agent spawning",
        "Service orchestration",
        "Inter-agent communication",
        "Load balancing",
      ],
      repo: "piddy-microservices",
      repoUrl: "https://github.com/burchdad/piddy-microservices",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Docker"],
      tier: 2,
    },
    {
      id: "ghost-drop",
      name: "📦 GhostDrop",
      shortName: "GhostDrop",
      role: "Productized Automation System",
      description: "AI funnel builder for businesses",
      features: [
        "Auto-generate sales funnels",
        "Chatbot builders",
        "Follow-up automation",
        "Airtable-based workflows",
        "Zero-code configuration",
      ],
      repo: "ghostdrop",
      repoUrl: "https://github.com/burchdad/ghostdrop",
      status: "Active Development",
      stack: ["JavaScript", "React", "Airtable"],
      tier: 2,
    },
    {
      id: "ghost-investor",
      name: "🧾 Ghost Investor AI",
      shortName: "GhostCFO",
      role: "Financial Analysis & Underwriting",
      description: "Investment analysis and deal evaluation engine",
      features: [
        "Deal structure analysis",
        "CapEx estimation",
        "ROI modeling",
        "Image-based underwriting",
        "Predictive modeling",
      ],
      repo: "ghost-investor-ai",
      repoUrl: "https://github.com/burchdad/ghost-investor-ai",
      status: "Active Development",
      stack: ["Python", "FastAPI", "Machine Learning"],
      tier: 2,
    },
    {
      id: "ghost-table",
      name: "📋 GhostTable",
      shortName: "GhostTable",
      role: "Airtable-Alternative Data Layer",
      description: "Lightweight database & table management for Ghost systems",
      features: [
        "Relational data management",
        "Real-time sync",
        "API integrations",
        "Query optimization",
      ],
      repo: "ghosttable",
      repoUrl: "https://github.com/burchdad/ghosttable",
      status: "Active Development",
      stack: ["TypeScript", "React", "Node.js"],
      tier: 2,
    },
  ],

  tier3: [
    {
      id: "investor-command-center",
      name: "🎯 Investor Command Center",
      shortName: "Investor Command Center",
      role: "R&D: Portfolio Orchestration",
      description: "Experimental multi-agent investment oversight system",
      features: [
        "Real-time portfolio tracking",
        "Multi-agent coordination",
        "Deal flow management",
      ],
      repo: "investor-command-center",
      repoUrl: "https://github.com/burchdad/investor-command-center",
      status: "Experimental",
      stack: ["Python", "FastAPI"],
      tier: 3,
    },
    {
      id: "tldr-agent",
      name: "📄 TLDR Agent",
      shortName: "TLDR Agent",
      role: "R&D: Content Intelligence",
      description: "Autonomous document analysis and summarization",
      features: [
        "PDF/document parsing",
        "AI summarization",
        "Key insights extraction",
      ],
      repo: "tldr-agent-demo",
      repoUrl: "https://github.com/burchdad/tldr-agent-demo",
      status: "Experimental",
      stack: ["TypeScript", "OpenAI"],
      tier: 3,
    },
    {
      id: "piddy-growth",
      name: "🧬 Piddy Growth",
      shortName: "Piddy Growth",
      role: "R&D: Autonomous Learning",
      description: "Self-improving agent learning system",
      features: [
        "Continuous skill acquisition",
        "Experience replay",
        "Performance optimization",
      ],
      repo: "piddy-growth",
      repoUrl: "https://github.com/burchdad/piddy-growth",
      status: "Experimental",
      stack: ["Python"],
      tier: 3,
    },
  ],

  solutions: [
    {
      id: "sales-automation",
      icon: "💼",
      title: "AI Sales Systems",
      subtitle: "Automated lead-to-close pipeline",
      description: "End-to-end sales automation powered by GhostMIND and GhostCRM. AI qualifies leads, sends follow-ups, schedules calls, and tracks pipeline—all without human touch.",
      impact: "5x faster lead conversion | 80% less manual work",
      use_case: "SaaS, e-commerce, B2B service businesses"
    },
    {
      id: "voice-agents",
      icon: "🎙️",
      title: "AI Voice Agents",
      subtitle: "24/7 autonomous customer interaction",
      description: "AI that answers calls, books appointments, handles customer service, and qualifies leads via natural conversation. Powered by Ghost Voice OS.",
      impact: "24/7 availability | Replaces call center staff",
      use_case: "Customer service, appointment booking, lead qualification"
    },
    {
      id: "credit-intelligence",
      icon: "💳",
      title: "Credit Intelligence Tools",
      subtitle: "AI-powered financial optimization",
      description: "GhostScore gives users actionable intelligence on credit optimization, helping them understand financial leverage points and improve credit faster.",
      impact: "Faster credit improvement | Better financial decisions",
      use_case: "FinTech, lending platforms, personal finance apps"
    },
    {
      id: "custom-ai",
      icon: "⚙️",
      title: "Custom AI Automation",
      subtitle: "Tailored autonomous systems",
      description: "Build custom AI agents and workflows using Ghost infrastructure. Connect to Zapier, APIs, databases, or any business tool. Scale your operations autonomously.",
      impact: "Cost savings | Scalability | Business automation",
      use_case: "Any business process that needs automation"
    }
  ],

  rdVision: [
    {
      id: "autonomous-coding",
      icon: "👨‍💻",
      title: "Autonomous Coding Agent",
      subtitle: "Piddy - Self-operating developer",
      description: "AI that writes, tests, and improves code autonomously. Self-healing architecture with multi-model fallback. The future of software development.",
      status: "Active Development"
    },
    {
      id: "offline-ai",
      icon: "🔌",
      title: "Offline AI Systems",
      subtitle: "USB-deployable autonomous AI",
      description: "AI systems that run completely offline on edge devices. No cloud dependency. Deploy to hardware, USB drives, or embedded systems.",
      status: "In Research"
    },
    {
      id: "multi-agent",
      icon: "🧬",
      title: "Multi-Agent Orchestration",
      subtitle: "Emergent AI coordination",
      description: "Advanced orchestration systems where AI agents coordinate autonomously, negotiate tasks, and self-optimize as a collective.",
      status: "In Development"
    },
    {
      id: "self-improving",
      icon: "🚀",
      title: "Self-Improving Pipelines",
      subtitle: "AI that evolves autonomously",
      description: "AI systems that learn, adapt, and improve continuously without human retraining. The foundation of truly autonomous business systems.",
      status: "Research Phase"
    }
  ],

  infrastructure: [
    {
      name: "Integrations",
      items: [
        "Stripe (payments & billing)",
        "Twilio (SMS & voice calls)",
        "Telnyx (carrier APIs)",
        "Mailchimp (email campaigns)",
        "Airtable (workflow logic)",
        "Zapier (automation backbone)",
        "Google Drive (report storage)",
        "People Data Labs (enrichment)",
      ]
    },
    {
      name: "AI Stack",
      items: [
        "OpenAI (GPT-4, 3.5)",
        "Anthropic (Claude)",
        "Local LLM (future)",
        "Voice AI",
      ]
    },
    {
      name: "Tech Stack",
      items: [
        "Python + FastAPI (backends)",
        "TypeScript + React (frontends)",
        "Node.js (services)",
        "Supabase (databases)",
        "Docker (containerization)",
      ]
    }
  ]
};
